### ISSUE TITLE
[Feature Request] Support infrastructure-tracking-schema

### ISSUE THREAD

**Issue by ninoseki** [ninoseki/mihari#250]
Implement a partial support of @3c7's [infrastructure-tracking-schema](https://github.com/3c7/infrastructure-tracking-schema) as an input.

### Mapping

```yml
title: Example Rule                                           # map to title
uuid: 11d0a892-b2eb-4df5-8b04-3a1272da6eed                    # ignore
author: Nils Kuhnert                                          # ignore
status: experimental                                          # ignore
created: 2020-10-09                                           # ignore
classification:
  - type: tlp                                                 # map to tags if type == tag
    value: white
condition:
  - AND:                                                      # supports only "OR" as a first step
    - type: "shodan"                                          # map to analyzer class
      query: "HTTP/1.1 200 X-Super-Suspicious-Header: Honk!"  # map to query
    - type: "passivedns"
      query: "regex:^\\w-\\w\\.site$"
```

### Example

```yml
title: example.com
uuid: 11d0a892-b2eb-4df5-8b04-3a1272da6eed
author: ninoseki
status: experimental
created: 2020-10-09
classification:
  - type: tag
    value: foo
  - type: tag
    value: bar
condition:
  - OR:
    - type: "shodan"
      query: "http.html_hash:-2087618365"
    - type: "censys"
      query: "ea8fac7c65fb589b0d53560f5251f74f9e9b243478dcb6b3ea79b5e36449c8d9"
    - type: "binaryedge"
      query: "web.body.sha256:ea8fac7c65fb589b0d53560f5251f74f9e9b243478dcb6b3ea79b5e36449c8d9"
```

This input will aggregate search results from Shodan, Censys, BinaryEdge and merge them as an alert. 

The input will be passed as a file or a string.

```bash
$ mihari search example.yml
# or
$ cat example.yml | xargs mihari search 
```
