### ISSUE TITLE
[BUG] Error while running mihari search using rules

### ISSUE THREAD

**Issue by r0ny123** [ninoseki/mihari#342]
### **Describe the bug**

Mihari is producing following error while searching using a rule. 
```
Traceback (most recent call last):
	13: from /usr/local/bin/mihari:23:in `<main>'
	12: from /usr/local/bin/mihari:23:in `load'
	11: from /var/lib/gems/3.0.0/gems/mihari-3.8.1/exe/mihari:8:in `<top (required)>'
	10: from /var/lib/gems/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	 9: from /var/lib/gems/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	 8: from /var/lib/gems/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	 7: from /var/lib/gems/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	 6: from /var/lib/gems/3.0.0/gems/mihari-3.8.1/lib/mihari/commands/search.rb:19:in `search_by_rule'
	 5: from /var/lib/gems/3.0.0/gems/mihari-3.8.1/lib/mihari/commands/search.rb:60:in `build_rule_analyzer'
	 4: from /var/lib/gems/3.0.0/gems/mihari-3.8.1/lib/mihari/commands/search.rb:60:in `new'
	 3: from /var/lib/gems/3.0.0/gems/mihari-3.8.1/lib/mihari/analyzers/rule.rb:50:in `initialize'
	 2: from /var/lib/gems/3.0.0/gems/mihari-3.8.1/lib/mihari/analyzers/rule.rb:134:in `validate_analyzer_configurations'
	 1: from /var/lib/gems/3.0.0/gems/mihari-3.8.1/lib/mihari/analyzers/rule.rb:134:in `each'
/var/lib/gems/3.0.0/gems/mihari-3.8.1/lib/mihari/analyzers/rule.rb:141:in `block in validate_analyzer_configurations': Censys is not configured correctly (ArgumentError)
```

### **Steps to reproduce**

- Create a valid configuration file and rule.
- run `mihari search example.yml --config config.yml`

I used the following rule and configuration (and validated both using `mihari validate` command)
- **rule**:
```yaml
title: example.com HTML
description: A rule to find hosts serve an HTML same as example.com
queries:
  - analyzer: censys
    query: services.http.response.body_hash:"sha1:4a3ce8ee11e091dd7923f4d8c6e5b5e41ec7c047"
allowed_data_types:
  - ip
```
- **configuration:**
```yaml
censys_id: foo
censys_secret: foo
database: mihari.db
```
### **Expected behavior**

Mihari should return expected values.

### **Actual behavior**

Mihari produces error as described above.

### **System Information:**

- OS: Ubuntu 20.4
- Ruby version: ruby 2.7.0p0
- Mihari version: Latest

### **Additional context**
The above error can't be reproduced in `mihari version 3.6.0`

**Comment by ninoseki** [comment]
I cannot reproduce your claim. 
The error says your a not configured the Censys analyzer correctly so I guess the path of the config file is wrong.

**Comment by r0ny123** [comment]
I rechecked the path of the config file.

**Comment by r0ny123** [comment]
@ninoseki for reference:
Using mihari 3.6.0 : https://github.com/r0ny123/mihari-test/runs/3643897339?check_suite_focus=true#step:5:85 (works perfect)
Using mihari 3.8.0 : https://github.com/r0ny123/mihari-test/runs/3643904921?check_suite_focus=true#step:5:4 (produces error)

**Comment by ninoseki** [comment]
Literally I have no idea what you are doing. Do not upload credentials in plain text. Use encrypted secrets.

**Comment by r0ny123** [comment]
Hello, it's just for test and don't worry about the credentials, I reset it before pasting it here.

**Comment by r0ny123** [comment]
So, this bug not is not going to be fixed?

**Comment by ninoseki** [comment]
Again, I cannot reproduce your claim. 
So I can do nothing. Also I guess your claim is not valid.

**Comment by r0ny123** [comment]
If you really can't reproduce this, then do you have any explanation why this is happening 
https://github.com/ninoseki/mihari/issues/342#issuecomment-922433457 

On that test repo, I have showed you that mihari functionality (i.e. `mihari search example.yml --config config.yml`) works perfectly fine in 3.6.0 but not in 3.8.0.

**Comment by doomedraven** [comment]
@ninoseki hello, is kinda the same what @r0ny123 tried to do

```
gem install mihari
```

* Config
```
censys_id: <id>
censys_secret: <secret>
database: mihari.db
```

* rule
```
title: example.com
description: test
queries:
  - analyzer: censys
    query: services.http.response.body_hash:"sha1:4a3ce8ee11e091dd7923f4d8c6e5b5e41ec7c047"
allowed_data_types:
  - ip
```

* search
`mihari search rule.yml --config config.yml`
