### ISSUE TITLE
[Feature Request] Enable API call throttling

### ISSUE THREAD

**Issue by ninoseki** [ninoseki/mihari#372]
## Background

Some APIs have a rate limitation. (e.g. 60 API calls / minute)
At the moment, Mihari does not care about it.
So I suggest introducing a new optional parameter (`interval`) for throttling while pagination.

## Implementation 

**CLI**

```bash
$ mihari analyze shodan ... --interval 1
```

**Rule**

```yaml
queries:
  - analyzer: shodan
    query: ...
    options;:
      interval: 1
```
