### ISSUE TITLE
[BUG] Mihari can't validate rule with `analyzer: zoomeye`

### ISSUE THREAD

**Issue by r0ny123** [ninoseki/mihari#443]
### **Describe the bug**

Mihari fails to validate rule when the analyzer is zoomeye.

### **Steps to reproduce**

-  Create a rule with an `analyzer: zoomeye`, eg.
 ```yaml
title: foo
description: foo
queries:
  - analyzer: zoomeye
    query: google
```
- save the above rule as `example.yml`.
- run `mihari validate rule example.yml`

### **Expected behavior**

Mihari Should validate it correctly.

### **Actual behavior**

`2022-03-21 13:52:34.276623 E [50395:8180 rule.rb:51] Mihari -- Failed to parse the input as a rule`

### **System Information:**

- OS: `Ubuntu 20.04`
- Ruby version: `3.0`
- Mihari version: `4.3.0`
