### ISSUE TITLE
[BUG] PassiveTotal analyzer not returning IPs while searching using SHA1 of a certificate

### ISSUE THREAD

**Issue by r0ny123** [ninoseki/mihari#446]
### **Describe the bug:**

According to [documentation](https://www.notion.so/PassiveTotal-7775706467bc438f8d3173e7ee148440), searching using `Hash (SSL certificate SHA1 fingerprint)` will return IP addresses associated with it. In this case, PassiveTotal analyzer not returning IPs while searching using sha1 of a certificate.

### **Steps to reproduce:**

- create example a rule mentioned below:
```yml
title: Ip's associated with cert c00a42e59d32acf2344a153c6de91896cde2a1c1(SHA1)
description: Ip's associated with cert c00a42e59d32acf2344a153c6de91896cde2a1c1(SHA1)
queries:
- analyzer: passivetotal
  query: c00a42e59d32acf2344a153c6de91896cde2a1c1
```
- save it and run `mihari search example.yml`
### **Expected behavior**

This should return some IP's associated with it.
Per RiskIQ, the cert has some IP's linked with it.
![image](https://user-images.githubusercontent.com/49360849/159514833-154e0376-3b67-4775-b6e3-6e7fadea1af4.png)

### **Actual behavior:**

The search doesn't return any results. (IP addresses) and prints the following output `Mihari -- There is no new artifact`.

### **System Information:**

- OS: `Ubuntu 20.04`
- Ruby version: `3.0`
- Mihari version: `4.3.0`

### **Additional context**

**_I also verified the above mentioned rule using `mihari validate rule` command and It said `Valid Format`._**
