### ISSUE TITLE
[Help] Parse CSV / TXT File

### ISSUE THREAD

**Issue by ssnkhan** [ninoseki/mihari#501]
### **Describe the bug**

I am trying to import a list of IPs from either of the following two sources:

* https://threatview.io/Downloads/High-Confidence-CobaltstrikeC2_IP_feed.txt
* https://threatview.io/Downloads/High-Confidence-CobaltStrike-C2%20-Feeds.txt

I am using the Feed parser, but struggling to do so. I do not believe this is a Mihari issue, but rather my inexperience with Ruby syntax.

### **Steps to reproduce**
``` yaml
title: Cobalt Strike C2
author: 
created_on: 2022-07-29
description: Imports high-fidelity and validated Cobalt Strike C2s from ThreatView.
tags: ["C2"]
allowed_data_types:
  - ip
ignore_old_artifacts: true
ignore_threshold: 30
queries:
  - analyzer: feed
    query: https://threatview.io/Downloads/High-Confidence-CobaltstrikeC2_IP_feed.txt
    http_request_method: "GET"
    selector: (See Below)
```

For the IP only feed, which features a single IP per line, I have tried to use `map { |v| v[1] }`. (and also tried `v[0]`. This is the error that gets returned:

```
Traceback (most recent call last):
	11: from /usr/local/bin/jr:23:in `<main>'
	10: from /usr/local/bin/jr:23:in `load'
	 9: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:86:in `<top (required)>'
	 8: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:86:in `each'
	 7: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:86:in `each'
	 6: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:86:in `each'
	 5: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:86:in `each'
	 4: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:86:in `each'
	 3: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:61:in `block in <top (required)>'
	 2: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:61:in `each'
	 1: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:62:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:62:in `parse': lexical error: invalid char in json text. (Yajl::ParseError)
                                       #Proactive Hunt C2 Threat Intel
                     (right here) ------^

```

For the feed in a more traditional CSV format, I have tried a selector of `map { |v| v[/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]/,0] }` to only capture IPs, but this also generates an error:

```
Traceback (most recent call last):
	11: from /usr/local/bin/jr:23:in `<main>'
	10: from /usr/local/bin/jr:23:in `load'
	 9: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:86:in `<top (required)>'
	 8: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:86:in `each'
	 7: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:86:in `each'
	 6: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:86:in `each'
	 5: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:86:in `each'
	 4: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:86:in `each'
	 3: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:61:in `block in <top (required)>'
	 2: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:61:in `each'
	 1: from /var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:62:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.7.0/gems/jr-cli-0.5.1/bin/jr:62:in `parse': lexical error: invalid char in json text. (Yajl::ParseError)
                                143.198.27.227 137.184.30.177 139.60.1
                     (right here) ------^
```

I have tried to test locally with `jr` with various regular expressions, but they all seem to fail.

### **Expected behavior**

Import IPs into Mihari.

### **Actual behavior**

Errors, as above.

### **Screenshots**

N/A

### **System Information:**

- OS: Ubuntu
- Ruby version: 2.7.0
- Mihari version: mihari-3.12.0 (Sorry! Manually patched with Shodan Fix: https://github.com/ninoseki/mihari/pull/425)

### **Additional context**

If I set `allowed_data_type` to `ip`, will that automatically filter out any entries which are not IPs? Unfortunately both feeds have both domains and IPs in the same field.

Would be grateful for any pointers, please!
