### ISSUE TITLE
[Feature Request] Suppress Enrichment

### ISSUE THREAD

**Issue by ssnkhan** [ninoseki/mihari#529]
As part of the Mihari processing pipeline, network indicators are enriched with whois/DNS information, but this invariably means that the sqlite database grows very quickly. The suggestion is to expose a preference / attribute via the DSL, that would allow users to opt-out of these enrichments. For example:

``` yaml
...
enrich-dns: false
enrich-geo: false
enrich-whois: false
...
```

Thank you for all your work on Mihari :)

**Comment by ninoseki** [comment]
Due to my laziness, I don't explain it but it is already possible by setting `enrichers`.

```yaml
title: test
description: foo
queries:
  - analyzer: shodan
    query: ip:1.1.1.1
allowed_data_types:
  - ip
enrichers: [] # defaults to ["whois", "ipinfo", "shodan", "google_public_dns"]
```

I will update docs.
